name: Deploy master docs

on:
  workflow_dispatch:

jobs:
  deploy-master-docs:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Deploy master docs
        env:
          VERSION: master
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_SLUG: ${{ github.repository }}
          DOCUMENTATION_REPO_SLUG: hikari-py/hikari-docs
        run: |
          bash scripts/deploy-pages.sh
